In [1]:
from pathlib import Path

import pandas as pd

In [4]:
delivered_df = pd.read_csv(
    r"data\processed\olist_delivered_item_level.csv"
)

order_item_df = pd.read_csv(
    r"data\processed\olist_order_item_level.csv"
)

C:\Users\PC2506\AppData\Local\Temp\ipykernel_28144\3301768106.py:1: DtypeWarning: Columns (0: is_late) have mixed types. Specify dtype option on import or set low_memory=False.
  delivered_df = pd.read_csv(

In [5]:
delivered_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total,customer_id,order_status,...,payment_value_total,payment_installments_max,payment_type_nunique,payment_types,review_score_mean,review_count,review_creation_min,review_answer_max,seller_customer_same_state,delivery_route
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,...,72.19,2.0,1.0,credit_card,5.0,1.0,2017-09-21 00:00:00,2017-09-22 10:57:03,False,SP -> RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,...,259.83,3.0,1.0,credit_card,4.0,1.0,2017-05-13 00:00:00,2017-05-15 11:34:13,True,SP -> SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,...,216.87,5.0,1.0,credit_card,5.0,1.0,2018-01-23 00:00:00,2018-01-23 16:06:31,True,MG -> MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,...,25.78,2.0,1.0,credit_card,4.0,1.0,2018-08-15 00:00:00,2018-08-15 16:39:01,True,SP -> SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,...,218.04,3.0,1.0,credit_card,5.0,1.0,2017-03-02 00:00:00,2017-03-03 10:54:59,False,PR -> SP

In [6]:
order_item_df.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,item_total,customer_id,order_status,...,payment_value_total,payment_installments_max,payment_type_nunique,payment_types,review_score_mean,review_count,review_creation_min,review_answer_max,seller_customer_same_state,delivery_route
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19,3ce436f183e68e07877b285a838db11a,delivered,...,72.19,2.0,1.0,credit_card,5.0,1.0,2017-09-21 00:00:00,2017-09-22 10:57:03,False,SP -> RJ
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83,f6dd3ec061db4e3987629fe6b26e5cce,delivered,...,259.83,3.0,1.0,credit_card,4.0,1.0,2017-05-13 00:00:00,2017-05-15 11:34:13,True,SP -> SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,...,216.87,5.0,1.0,credit_card,5.0,1.0,2018-01-23 00:00:00,2018-01-23 16:06:31,True,MG -> MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78,d4eb9395c8c0431ee92fce09860c5a06,delivered,...,25.78,2.0,1.0,credit_card,4.0,1.0,2018-08-15 00:00:00,2018-08-15 16:39:01,True,SP -> SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04,58dbd0b2d70206bf40e62cd34e84d795,delivered,...,218.04,3.0,1.0,credit_card,5.0,1.0,2017-03-02 00:00:00,2017-03-03 10:54:59,False,PR -> SP